# Generated by Django 4.2.7 on 2023-11-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_number', models.AutoField(primary_key=True, serialize=False)),
                ('paper_number', models.IntegerField()),
                ('content', models.CharField(blank=True, max_length=500)),
                ('wrote', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('nickname', models.ForeignKey(db_column='nickname', on_delete=django.db.models.deletion.CASCADE, to='users.user', to_field='nickname')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
