# Generated by Django 4.2.7 on 2023-11-23 06:57

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_nickname'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('nickname',), name='message_nickname'),
        ),
    ]
