# Generated by Django 4.2.7 on 2023-11-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_message_message_nickname'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_nickname',
        ),
    ]
