# Generated by Django 4.2.7 on 2023-11-23 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_remove_message_message_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='wrote',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
