# Generated by Django 4.2.7 on 2023-11-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_rolling_paper_nickname'),
        ('message', '0007_alter_message_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='paper_number',
            field=models.ForeignKey(db_column='paper_number', on_delete=django.db.models.deletion.CASCADE, to='papers.rolling_paper'),
        ),
    ]
