# Generated by Django 4.2.7 on 2023-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('papers', models.IntegerField()),
                ('messages', models.IntegerField()),
                ('joined', models.DateTimeField()),
                ('modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
