# Generated by Django 4.2.7 on 2023-11-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolling_paper',
            name='nickname',
            field=models.ForeignKey(db_column='nickname', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='users.user', to_field='nickname'),
        ),
    ]
