# Generated by Django 4.2.7 on 2023-11-23 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_remove_rolling_paper_paper_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolling_paper',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rolling_paper',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
