# Generated by Django 4.2.7 on 2023-11-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0006_alter_rolling_paper_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolling_paper',
            name='nickname',
            field=models.ForeignKey(db_column='nickname', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
