# Generated by Django 4.2.7 on 2023-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_rolling_paper_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolling_paper',
            name='users',
            field=models.IntegerField(default=0),
        ),
    ]
